Update trace_connectors_user_guide.md
relativitydev/relativity-trace-documentation pull request #47
Opened 2020-02-13 21:30 UTC by atien23

2020-02-13 23:40 UTC, atien23 commented
Just submitted PR

2020-02-17 17:08 UTC, mishakogan requested changes

2020-02-17 17:08 UTC, mishakogan commented on docs/trace_connectors_user_guide.md
> +1.  You must first create an Integration Point Profile if you have not already done so for the data source type you're attempting to connect to. The Integration Point Profile is used to map fields in
@atien23 why are referencing PDF? There should be a section in the main document on setting up Integration Point Profile and that section should be referenced here

2020-02-18 20:20 UTC, mishakogan approved these changes

2020-02-18 20:20 UTC, merged